language: "node_js"

node_js:
 - "node"

install:
 - npm install

services:
 - mysql

before_install:
 - mysql -u root --password="" < fulbito-server/test/travis.sql

before_script:
 - cd fulbito-server && npm start

script: cd fulbito-server && npm test