language: "node_js"

node_js:
 - "node"

services:
 - mysql

before_install:
 - mysql -u root --password="" < fulbito-server/test/travis.sql

install:
 - cd fulbito-server && npm install

before_script:
 - node index.js

script: npm test   