language: "node_js"

node_js:
 - "node"

services:
 - mysql

before_install:
 - mysql -u root --password="" < fulbito-server/test/travis.sql

install:
 - cd fulbito-server && npm install

script: node index.js & npm test