language: "node_js"

node_js:
 - "node"

services:
 - mysql

before_install:
 - mysql -u root --password="" < fulbito-server/test/travis.sql

install:
 - npm install

before_script:
 - node fulbito-server/index.js

script: cd fulbito-server && npm test